sudo: required
dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix

language: php

jobs:
  include:
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.2.7 MAGENTO_EDITION=community
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.2.8 MAGENTO_EDITION=community
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.2.9 MAGENTO_EDITION=community
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then composer config -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD ; fi
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json

install:
  - composer install --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache
